# Change these first
owner: simonmage # Your GitHub organization or username, where this repository lives
repo: newwave-status-page # The name of this repository

sites:
  - name: Drasl Multiplayer Session Service
    url: https://auth.newwave.fun/session
    expectedStatusCodes:
      - 404
  - name: Drasl Authserver
    url: https://auth.newwave.fun/auth
    expectedStatusCodes:
      - 200
  - name: Mojang Multiplayer Session Service
    url: http://session.minecraft.net
    expectedStatusCodes:
      - 404
  - name: Skins
    url: https://auth.newwave.fun
    expectedStatusCodes:
      - 200
  - name: "Drasl's Public API"
    url: https://auth.newwave.fun/auth
  - name: Main Drasl Auth Website
    url: https://auth.newwave.fun/
    expectedStatusCodes:
      - 200
      - 200
  - name: drasl API
    url: https://auth.newwave.fun/session/minecraft/profile
    expectedStatusCodes:
      - 404

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /newwave-status-page
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: NewWave Status Page
  introTitle: "This page is used by NewWave Launcher to get Drasl status."
  introMessage: We are not Mojang/Microsoft
  navbar:
    - title: Home
      href: /newwave-status-page
    - title: NewWave Launcher
      href: https://github.com/simonmage/newwavelauncherreleaser

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
